name: eye_spy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^2.0.1
  equatable: ^1.0.0
  chewie: ^0.9.8+1
  http: ^0.12.0+2
  path_provider: ^1.4.4
  shared_preferences: ^0.5.4+5
  flushbar: ^1.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png